name: Python application

on: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Run scrapper
      run: |
        python scrapper.py
    - name: Commit 
      run: |
        git config --global user.email "chrsep@protonmail.com"
        git config --global user.name "Chrisando Pramudhita"
        git add *
        git commit -m "Update data"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

