name: Python application

on: 
  push:
    branches: 
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Run scrapper
      run: |
        python scrapper.py
    - name: Commit 
      run: |
        git add *
        git commit -m "Update data"
        git push

